name: Build & Deploy Vite Site

on:
  push:
    branches:
      - main  # adjust if needed

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # or your version

      - name: Install dependencies
        working-directory: ./career-launch
        run: npm ci  # faster & more reproducible than install

      - name: Build the site
        working-directory: ./career-launch
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan ehb-match.me >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no dev-deploy-ehb-match@ehb-match.me "echo SSH OK"

      - name: Deploy via rsync
        working-directory: ./career-launch
        run: |
          rsync -avz --delete -e "ssh" ./dist/ deploy-ehb-match@ehb-match.me:/var/www/ehb-match.me
