name: Build & Deploy Vite Site

on:
  push:
    branches:
      - dev  # adjust if needed

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # or your version

      - name: Install dependencies
        working-directory: ./career-launch
        run: npm ci  # faster & more reproducible than install

      - name: Build the site
        working-directory: ./career-launch
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEV_DEPLOY_KEY }}

      - name: Deploy via rsync
        working-directory: ./career-launch
        run: |
          rsync -avz --delete ./dist/ dev-deploy-ehb-match@ehb-match.me:/var/www/dev.ehb-match.me
